sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
before_install:
  - gem update --system
  - gem install bundler --conservative --no-document -v "~> 2.0"
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    # Run Danger only once, on 2.6.0
    - rvm: 2.6.0
      script: bundle exec danger
