version: '{build}'

skip_tags: true

environment:
  matrix:
    - ruby_version: "25"
    - ruby_version: "25-x64"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem update --system
  - gem install bundler --no-document
  - bundle install --retry=3

test_script:
  - bundle exec rake

build: off
